import { generateLanding } from "./landing.js";
import { displayName, slugify } from "../slug.js";
import type { GeneratedFiles, StarterFramework } from "../types.js";

function nextFiles(name: string, landing: GeneratedFiles): Record<string, string> {
  const slug = slugify(name);
  return {
    "package.json": JSON.stringify(
      {
        name: slug,
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "^15.3.1",
          react: "^19.1.0",
          "react-dom": "^19.1.0",
        },
        devDependencies: {
          typescript: "^5.8.3",
          "@types/react": "^19.1.2",
          "@types/node": "^22.15.3",
        },
      },
      null,
      2,
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "es2022"],
          jsx: "preserve",
          module: "esnext",
          moduleResolution: "bundler",
          strict: true,
          noEmit: true,
          incremental: true,
          esModuleInterop: true,
          resolveJsonModule: true,
          isolatedModules: true,
          plugins: [{ name: "next" }],
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      },
      null,
      2,
    ) + "\n",
    "next.config.ts": `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n`,
    "next-env.d.ts": `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n`,
    "app/globals.css": landing.files["sitestencil.css"]!,
    "app/layout.tsx": `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(name)},
  description: "Street-tech DeFi landing generated by SiteStencil",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    "app/page.tsx": landing.files["LandingPage.tsx"]!.replace(
      `import "./sitestencil.css";\n\n`,
      "",
    ),
    "sitestencil.config.json": landing.files["sitestencil.config.json"]!,
    "motion.ts": landing.files["motion.ts"]!,
    "README.md": `# ${name}

Next.js starter from SiteStencil.

\`\`\`bash
npm install
npm run dev
\`\`\`

Street-tech tokens live in \`app/globals.css\`. Do not restyle this into purple SaaS.
`,
  };
}

function viteFiles(name: string, landing: GeneratedFiles): Record<string, string> {
  const slug = slugify(name);
  return {
    "package.json": JSON.stringify(
      {
        name: slug,
        private: true,
        type: "module",
        scripts: {
          dev: "vite",
          build: "tsc -b && vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^19.1.0",
          "react-dom": "^19.1.0",
        },
        devDependencies: {
          "@types/react": "^19.1.2",
          "@types/react-dom": "^19.1.2",
          "@vitejs/plugin-react": "^4.4.1",
          typescript: "^5.8.3",
          vite: "^6.3.4",
        },
      },
      null,
      2,
    ) + "\n",
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          module: "ESNext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
          noEmit: true,
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n",
    "vite.config.ts": `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
    "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    "src/main.tsx": `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import Landing from "./LandingPage";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <Landing />
  </StrictMode>,
);
`,
    "src/LandingPage.tsx": landing.files["LandingPage.tsx"]!,
    "src/sitestencil.css": landing.files["sitestencil.css"]!,
    "src/motion.ts": landing.files["motion.ts"]!,
    "sitestencil.config.json": landing.files["sitestencil.config.json"]!,
    "README.md": `# ${name}

Vite + React starter from SiteStencil.

\`\`\`bash
npm install
npm run dev
\`\`\`

Street-tech tokens live in \`src/sitestencil.css\`. Keep the brick.
`,
  };
}

export function generateStarter(options: {
  name: string;
  framework: StarterFramework;
  preset?: string;
}): GeneratedFiles {
  const name = displayName(options.name);
  const landing = generateLanding({ name, preset: options.preset, format: "tsx" });
  const files =
    options.framework === "next" ? nextFiles(name, landing) : viteFiles(name, landing);
  return {
    files,
    recipeIds: landing.recipeIds,
    preset: landing.preset,
    name,
  };
}
