import type { LandingPreset, Recipe } from "./types.js";

export const recipes: Recipe[] = [
  {
    id: "brick-vault-hero",
    title: "Dark brick vault hero",
    category: "hero",
    summary: "Full-bleed soot-brick hero with cyan/gold lockup and a classified HUD kicker.",
    whenToUse: "Protocol or vault landings. First screen. Never a centered SaaS headline.",
    tokens: ["brick.900", "neon.cyan", "neon.gold", "type.display"],
    motion: "hud-in",
    do: ["Flush type left", "Lockup of two neon CTAs", "HUD kicker above the display face"],
    dont: ["Center-align a soft gradient headline", "Use Inter + purple mesh"],
    snippetId: "brick-vault-hero",
  },
  {
    id: "hud-wallet-connect",
    title: "HUD wallet connect",
    category: "hud",
    summary: "Scanlined connect panel with corner ticks, live chip, and injected / social rows.",
    whenToUse: "Connect gates, callback pages, wallet-first landings.",
    tokens: ["glass.fill", "neon.cyan", "type.hud"],
    motion: "hud-in",
    do: ["Treat connect as a terminal, not a modal blob", "Show network + session state"],
    dont: ["Generic rounded Connect Wallet pill on a white card"],
    snippetId: "hud-wallet-connect",
  },
  {
    id: "neon-ticker-bar",
    title: "Neon ticker bar",
    category: "chrome",
    summary: "Magenta/cyan marquee of pairs, funding, and liquidations.",
    whenToUse: "Any market-facing page. Pin under nav or above footer.",
    tokens: ["neon.magenta", "type.hud"],
    motion: "ticker",
    do: ["ALL CAPS mono", "Duplicate the track for a seamless loop"],
    dont: ["Stock ticker fonts or blue chips"],
    snippetId: "neon-ticker-bar",
  },
  {
    id: "glass-swap-card",
    title: "Glass swap card",
    category: "card",
    summary: "Frosted brick glass swap with gold focus rings and HUD labels.",
    whenToUse: "DEX / aggregator heroes and dashboards.",
    tokens: ["glass.fill", "neon.gold", "neon.cyan"],
    motion: "hud-in",
    do: ["Keep radius at 2–4px", "HUD labels over pretty placeholders"],
    dont: ["16px rounded white swap card"],
    snippetId: "glass-swap-card",
  },
  {
    id: "cyan-gold-cta",
    title: "Cyan-gold CTA stack",
    category: "chrome",
    summary: "Primary cyan fill + ghost gold. Magenta reserved for danger.",
    whenToUse: "Hero lockups, empty states, launch CTAs.",
    tokens: ["neon.cyan", "neon.gold"],
    motion: "pulse-neon",
    do: ["Pair fill + ghost", "Letterspace like a stencil"],
    dont: ["Single indigo filled button"],
    snippetId: "cyan-gold-cta",
  },
  {
    id: "magenta-alert-toast",
    title: "Magenta alert toast",
    category: "feedback",
    summary: "Liquidation / oracle / pause warning with a hot pulse.",
    whenToUse: "Risk, pause, or failed-tx states.",
    tokens: ["neon.magenta", "glass.fillHot"],
    motion: "warn-flash",
    do: ["One urgent sentence + a code", "Pulse the magenta glow only"],
    dont: ["Red Bootstrap alerts"],
    snippetId: "magenta-alert-toast",
  },
  {
    id: "token-grid",
    title: "Token brick grid",
    category: "data",
    summary: "Asset tiles on mortar-dark glass with pair, APY, and depth.",
    whenToUse: "Markets, launchpads, watchlists.",
    tokens: ["brick.700", "neon.gold", "glass.borderCyan"],
    motion: "hud-in",
    do: ["Tight 3–4 column grid", "Mono stats"],
    dont: ["Pinterest-style image cards"],
    snippetId: "token-grid",
  },
  {
    id: "protocol-stats-hud",
    title: "Protocol stats HUD",
    category: "hud",
    summary: "TVL, 24h volume, active vaults, and chain as four HUD cells.",
    whenToUse: "Below the hero on any protocol landing.",
    tokens: ["neon.gold", "type.display", "type.hud"],
    motion: "count-up",
    do: ["Gold figures, cyan labels", "Hard corners"],
    dont: ["Soft metric pills with icons from a SaaS kit"],
    snippetId: "protocol-stats-hud",
  },
  {
    id: "street-nav",
    title: "Street-tech nav",
    category: "nav",
    summary: "Stencil wordmark, mono links, gold brand, cyan underline.",
    whenToUse: "Every generated landing.",
    tokens: ["neon.gold", "neon.cyan", "type.hud"],
    motion: "hud-in",
    do: ["Keep it thin and industrial", "Pair with a live wallet chip"],
    dont: ["Fat glass nav with a gradient logo"],
    snippetId: "street-nav",
  },
  {
    id: "scanline-overlay",
    title: "Scanline overlay",
    category: "motion",
    summary: "CRT hatch over the brick, multiply-blended, slow sweep.",
    whenToUse: "Always-on atmosphere. Keep pointer-events none.",
    tokens: ["brick.950"],
    motion: "scanline",
    do: ["Subtle. Atmosphere, not a filter meme"],
    dont: ["Heavy VHS that kills contrast"],
    snippetId: "scanline-overlay",
  },
  {
    id: "brick-footer",
    title: "Brick footer",
    category: "chrome",
    summary: "Mortar rule, mono legal, chain ids, SiteStencil mark.",
    whenToUse: "Close every landing.",
    tokens: ["brick.mortar", "type.hud"],
    motion: "hud-in",
    do: ["Uppercase micro type", "Chain + docs + status"],
    dont: ["Big pastel sitemap"],
    snippetId: "brick-footer",
  },
  {
    id: "wallet-status-chip",
    title: "Wallet status chip",
    category: "hud",
    summary: "Live pulse + truncated address + chain tag.",
    whenToUse: "Nav trailing slot and connected states.",
    tokens: ["neon.cyan", "type.hud"],
    motion: "pulse-neon",
    do: ["First 4 / last 4", "Pulse only when live"],
    dont: ["Blockie + long hex in body type"],
    snippetId: "wallet-status-chip",
  },
  {
    id: "tvl-counter",
    title: "TVL counter",
    category: "data",
    summary: "Single oversized gold readout with a classified caption.",
    whenToUse: "Hero side-column or stats break.",
    tokens: ["neon.gold", "type.display"],
    motion: "count-up",
    do: ["One number, huge", "Caption in HUD mono"],
    dont: ["Tiny grey KPI with an up-arrow icon"],
    snippetId: "tvl-counter",
  },
  {
    id: "pool-card",
    title: "Liquidity pool card",
    category: "card",
    summary: "Pair, fee tier, depth, and a gold deposit action.",
    whenToUse: "Farm and pool directories.",
    tokens: ["glass.fill", "neon.gold"],
    motion: "hud-in",
    do: ["Fee as a stencil stamp", "Depth in mono"],
    dont: ["Illustrated coins"],
    snippetId: "pool-card",
  },
  {
    id: "chain-selector",
    title: "Chain selector HUD",
    category: "form",
    summary: "Multi-chain switch as a gold-border select, not a globe icon.",
    whenToUse: "Swap, vault, and connect surfaces.",
    tokens: ["neon.gold", "type.hud"],
    motion: "hud-in",
    do: ["Name the chain in mono", "Show the id"],
    dont: ["Rainbow network modal"],
    snippetId: "chain-selector",
  },
  {
    id: "gas-meter",
    title: "Gas meter",
    category: "data",
    summary: "Priority fee as a gold-to-magenta bar with a numeric HUD.",
    whenToUse: "Tx confirm and swap footers.",
    tokens: ["neon.gold", "neon.magenta"],
    motion: "pulse-neon",
    do: ["Bar + gwei number", "Warn in magenta past 70%"],
    dont: ["Leaf-green eco badges"],
    snippetId: "gas-meter",
  },
  {
    id: "nft-drop-banner",
    title: "NFT drop banner",
    category: "hero",
    summary: "Magenta/gold classified drop strip with a countdown kicker.",
    whenToUse: "Mints, allowlists, seasonal drops.",
    tokens: ["neon.magenta", "neon.gold"],
    motion: "glitch",
    do: ["Treat it like a street poster", "Countdown in mono"],
    dont: ["OpenSea-style preview tiles as the hero"],
    snippetId: "nft-drop-banner",
  },
  {
    id: "yield-vault-panel",
    title: "Yield vault panel",
    category: "card",
    summary: "Deposit / withdraw tabs, APY stamp, and a gold commit.",
    whenToUse: "Vault and farm landings.",
    tokens: ["glass.fill", "neon.gold", "neon.cyan"],
    motion: "hud-in",
    do: ["Tab as HUD, not pill group", "Show cap remaining"],
    dont: ["Friendly savings-app copy"],
    snippetId: "yield-vault-panel",
  },
  {
    id: "street-form",
    title: "Street-tech form",
    category: "form",
    summary: "Allowlist / waitlist fields with gold borders and cyan focus.",
    whenToUse: "Waitlists, refer codes, support.",
    tokens: ["neon.gold", "neon.cyan", "type.hud"],
    motion: "hud-in",
    do: ["Labels in micro HUD", "Hard focus ring"],
    dont: ["Floating labels on a white sheet"],
    snippetId: "street-form",
  },
  {
    id: "glitch-heading",
    title: "Glitch display heading",
    category: "motion",
    summary: "Split cyan/magenta shadow on Chakra Petch display type.",
    whenToUse: "Hero titles and drop names.",
    tokens: ["neon.cyan", "neon.magenta", "type.display"],
    motion: "glitch",
    do: ["Short words. Stencil energy", "Rare twitch, not constant seizure"],
    dont: ["Gradient filled text"],
    snippetId: "glitch-heading",
  },
];

export const landingPresets: Record<
  LandingPreset,
  { label: string; recipeIds: string[]; kicker: string; blurb: string }
> = {
  vault: {
    label: "Vault landing",
    recipeIds: [
      "scanline-overlay",
      "street-nav",
      "neon-ticker-bar",
      "brick-vault-hero",
      "glitch-heading",
      "cyan-gold-cta",
      "protocol-stats-hud",
      "tvl-counter",
      "yield-vault-panel",
      "brick-footer",
    ],
    kicker: "CLASSIFIED VAULT // BRICK SECTOR",
    blurb: "Non-custodial brick vaults. Cyan rails. Gold settlement. No purple dashboard.",
  },
  swap: {
    label: "Swap HUD",
    recipeIds: [
      "scanline-overlay",
      "street-nav",
      "neon-ticker-bar",
      "glass-swap-card",
      "chain-selector",
      "gas-meter",
      "token-grid",
      "brick-footer",
    ],
    kicker: "ROUTE TABLE // LIVE PAIRS",
    blurb: "Glass swap over soot brick. Gold focus. Magenta only when the route breaks.",
  },
  wallet: {
    label: "Wallet gate",
    recipeIds: [
      "scanline-overlay",
      "street-nav",
      "hud-wallet-connect",
      "wallet-status-chip",
      "magenta-alert-toast",
      "brick-footer",
    ],
    kicker: "SESSION GATE // HUD AUTH",
    blurb: "Connect as a terminal. Injected, social, or hardware. Live chip when the session holds.",
  },
  launch: {
    label: "Token launch",
    recipeIds: [
      "scanline-overlay",
      "street-nav",
      "nft-drop-banner",
      "glitch-heading",
      "cyan-gold-cta",
      "token-grid",
      "street-form",
      "brick-footer",
    ],
    kicker: "ALLOWLIST OPEN // MAGENTA DROP",
    blurb: "Street-poster launch. Countdown, allowlist form, token grid. Not a Notion site.",
  },
  yield: {
    label: "Yield farm",
    recipeIds: [
      "scanline-overlay",
      "street-nav",
      "protocol-stats-hud",
      "pool-card",
      "yield-vault-panel",
      "gas-meter",
      "brick-footer",
    ],
    kicker: "YIELD RAIL // GOLD BRICK",
    blurb: "Farms as industrial panels. Depth, fee stamp, cap remaining.",
  },
};

export function getRecipe(id: string): Recipe | undefined {
  return recipes.find((recipe) => recipe.id === id);
}

export function listRecipes(category?: Recipe["category"]): Recipe[] {
  return category ? recipes.filter((recipe) => recipe.category === category) : recipes;
}

export function resolvePreset(preset?: string): LandingPreset {
  if (preset && preset in landingPresets) {
    return preset as LandingPreset;
  }
  return "vault";
}
